### PR TITLE
Add vote.planetfinance.io

### PR DESCRIPTION
**Pull request by planetfinance**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [X] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — COMMENTED** [review]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

**Comment by planetfinance** [comment]
Hi there! How can I solve this conflict? I tried doing a second pull request but the same keeps happening. Maybe adding the line in the middle of the file rather than the last line like you suggested to another request? Thank you!

**Comment by gokaiorg** [comment]
> Hi there! How can I solve this conflict? I tried doing a second pull request but the same keeps happening. Maybe adding the line in the middle of the file rather than the last line like you suggested to another request? Thank you!

Hey @planetfinance 
To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Comment by planetfinance** [comment]
Just pushed the fixed conflict from a local computer :) hopefully it works now. Thank you!

**Comment by gokaiorg** [comment]
Unfortunately nope :) Never-mind i'll do it. Thank you.

**Pull request closed without merging**
