### PR TITLE
Add strategies for cream space

### PR DESCRIPTION
**Pull request by bun919tw**
**Add strategies for cream space**  
  
Etherscan: https://etherscan.io/address/0x2ba592F78dB6436527729929AAf6c908497cB200
CoinGecko: https://www.coingecko.com/en/coins/cream
Website: https://app.cream.finance/
Twitter: https://twitter.com/CreamdotFinance

1. Balancer pool

### CODE REVIEW

**Comment by gokaiorg** [comment]
We've made a major global update, please pull before commit again your changes or create a new pull request. Thank you.

**Comment by jeremyHD** [comment]
@gokaiorg PR updated :)

**Comment by gokaiorg** [comment]
@jeremyHD Sorry we've made a new major global update! You should pull again and following the documentation fleshly updated. https://docs.snapshot.page/guides/create-a-space#3-space-metadata
@bonustrack Could you take a good look at this strategy? Thank you.

**Comment by bun919tw** [comment]
Hi @gokaiorg 
I already updated the PR.

Oh, if you could first check another [PR at snapshot.js](https://github.com/snapshot-labs/snapshot.js/pull/15), it will be much appreciated! Thanks :)

**Comment by bonustrack** [comment]
The issue is that results are calculated in user browser, having 6 strategies mean there will be (at least) 6 requests being sent in same time from the user browser. It may get too heavy to process for the browser, it would be better if you can move some of the logic to a smart contract and reduce the number of strategies to 2-3 max.

**Comment by bun919tw** [comment]
Got it. Thanks for the reply. Will improve this.

**Comment by bun919tw** [comment]
Hi @bonustrack ,
We will combine the contract calls together. In the meantime, we want to support the balancer first. Thanks a lot.

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
