### PR TITLE
Add IDLE space

### PR DESCRIPTION
**Pull request by bugduino**

### CODE REVIEW

**Comment by gokaiorg** [comment]
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

**Comment by bugduino** [comment]
I did the step 1 and 2 of the new Beta doc but the content of the settings page isn't changed, is there anything else I have to do?
Thanks

**Comment by gokaiorg** [comment]
We have made a major update. You should now use ENS and IPFS method to create your space. Here is the guide: https://docs.snapshot.page/guides/create-a-space. I'm closing this PR for now, you will need to open a new one to add your space images. Thank you.
For further help please ask in the `#helpdesk` Discord channel.

**Comment by bugduino** [comment]
Updated the PR [here](https://github.com/snapshot-labs/snapshot-spaces/pull/548), settings have been updated using ENS

**Pull request closed without merging**
