### PR TITLE
Add missing comma

### PR DESCRIPTION
**Pull request by ChaituVR**

### CODE REVIEW

**Review by wa0x6e — APPROVED** [review]
utAck

**Comment by ChaituVR** [comment]
yea true, https://github.com/snapshot-labs/snapshot-spaces/pull/2611 but somehow no action was run on this PR 🤔

**Comment by wa0x6e** [comment]
Seems like this action is not run when PR is opened by someone not from the team.

We could either: 

- Allow this action to always be run for PR opened by external contributor
- Prevent the merge on `master` to continue when workflows are failing (I prefer this, and I think we're already using this on some repo)

**Comment by ChaituVR** [comment]
> Prevent the merge on master to continue when workflows are failing (I prefer this, and I think we're already using this on some repo)

For this @bonustrack need to change `Branch protection rule` settings similar to here https://github.com/snapshot-labs/snapshot.js/settings/branch_protection_rules/17997175
and add [this action](https://github.com/snapshot-labs/snapshot-spaces/blob/master/.github/workflows/jsoncheck.yml) mandatory
Untitled 2

**Pull request merged**
