### PR TITLE
feat(spaces): add Ditto.money

### PR DESCRIPTION
**Pull request by developerfred**
- [x] Add [Ditto.money](https://ditto.money)  - dittomoney.eth
- [x] https://snapshot.page/#/dittomoney.eth/
- [x] logo size 45kb

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
- I cannot find your space https://snapshot.page/#/dittomoney.eth, did you create it already?
- Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.
- The images file size should not exceed 50KB. Please reduce their weight.

**Comment by developerfred** [comment]
@gokaiorg I'm going to create it, I was waiting for my strategy to merge. I'll create a default strategy after I change it when you accept the pull request. 

I'm going to decrease the size of the logo now

**Comment by developerfred** [comment]
@gokaiorg done, we just need to wait for the 3 minutes of spread from snapshot.page for dittomoney.eth to be live.

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
Ok I merged, your skin should be live soon! Thank you.

**Comment by developerfred** [comment]
Thanks @gokaiorg!

**Pull request merged**
