### PR TITLE
Add SpiceDAO Avatar & Space

### PR DESCRIPTION
**Pull request by bitsandtea**
Add SpiceDAO Avatar & Space

### CODE REVIEW

**Review by gokaiorg — COMMENTED** [review]
I cannot find your space https://snapshot.page/#/spicedao.eth, did you create it already?

**Comment by bitsandtea** [comment]
I have submitted my settings and it says "Settings are in" but I don't see any update on the page. There are a bunch of errors in the console when I try to access https://snapshot.page/#/spicedao.eth. Any ideas? @gokaiorg

**Comment by gokaiorg** [comment]
> https://snapshot.page/#/spicedao.eth

@bitsandtea Did you try clear browser caches or in another browser?

**Comment by bitsandtea** [comment]
> > https://snapshot.page/#/spicedao.eth
> 
> @bitsandtea Did you try clear browser caches or in another browser?

There is a bug that Fabien from discord channel is working on.. until that one is fixed lets leave this paused.

**Comment by bitsandtea** [comment]
Its up and running now @gokaiorg

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
