### PR TITLE
Updated halodao.eth logo

### PR DESCRIPTION
**Pull request by mystbrent**
#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
The images file size should not exceed 50KB. Please reduce their weight.

**Comment by mystbrent** [comment]
> The images file size should not exceed 50KB. Please reduce their weight.

The images have been updated to reduce file sizes. Thank you

**Review by gokaiorg — CHANGES_REQUESTED** [review]
- There is a conflict in your PR, can you resolve it?
- To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.

`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Comment by mystbrent** [comment]
> * There is a conflict in your PR, can you resolve it?
> * To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
> 
> `git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
> `git fetch upstream`
> `git checkout master`
> `git merge upstream/master`

I have resolved the merge conflicts in the latest commit. Thank you for sharing the instructions saved me time.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
