### PR TITLE
Update domains.json gov.richquack.com to richquack.eth

### PR DESCRIPTION
**Pull request by kulwantquack**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ V] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by kulwantquack — COMMENTED** [review]
Add custom domain for your space

**Review by gokaiorg — CHANGES_REQUESTED** [review]
We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.
image

**Comment by kulwantquack** [comment]
Hi @gokaiorg how about the domain? Did you approve it yet? anything wrong with the custom domain?

**Comment by kulwantquack** [comment]
> We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.
> image

yes just update from settings.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
