### PR TITLE
Index: Update strategy to read from unclaimed Index balance

### PR DESCRIPTION
**Pull request by inje**
Adds strategies to read INDEX balances from Uniswap and unclaimed INDEX from the [Index liquidity mining rewards contract](https://etherscan.io/address/0x8f06FBA4684B5E0988F215a47775Bb611Af0F986).

Credits to @ncitron

### CODE REVIEW

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
@inje Your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?

**Comment by inje** [comment]
Yes, that’s okay. Is there a way to keep the proposals after updating strategies?

**Comment by gokaiorg** [comment]
@inje Yes, you could rename your existing space to something like index-archive and create a new index space.

**Comment by inje** [comment]
Okay. We can merge this in for now then I'll create a follow up PR when we move to the ENS method to maintain the Snapshot page.

**Comment by inje** [comment]
@gokaiorg When will the deployment take place?

**Comment by controtie** [comment]
@gokaiorg the Index snapshot page appears to still be showing our previous proposals. Does that mean the new strategy hasn't been deployed yet?
Is there any way to tell if our updated strategy is live?

**Comment by gokaiorg** [comment]
@controtie Yes we are waiting for a deploy. Thank you for your patience.

**Pull request merged**
