### PR TITLE
add Backd skin

### PR DESCRIPTION
**Pull request by chase-manning**
#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

image

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
To create your skin will also need to list your skin on this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

**Comment by chase-manning** [comment]
@gokaiorg Thanks! Have added it 😄

**Comment by gokaiorg** [comment]
> @gokaiorg Thanks! Have added it 😄

@chase-manning You will need to add also the skin name in the export default object line 270 in the `index.js` file.

**Comment by chase-manning** [comment]
> > @gokaiorg Thanks! Have added it 😄
> 
> @chase-manning You will need to add also the skin name in the export default object line 270 in the `index.js` file.

@gokaiorg 

Sorry! Thanks have added that!

**Comment by chase-manning** [comment]
@gokaiorg I think this one should be good to go now! 🚀

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
