### PR TITLE
update the index.json

### PR DESCRIPTION
**Pull request by zacharyer**
update the index.json

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
The images file size should not exceed 50KB. Please reduce their weight.

**Comment by zacharyer** [comment]
> The images file size should not exceed 50KB. Please reduce their weight.

hey, the single image only 46kb~

**Comment by gokaiorg** [comment]
You may added this 2 images by mistake, you should remove them.
image

**Comment by zacharyer** [comment]
> You may added this 2 images by mistake, you should remove them.
> image

Oh thx. removed all~

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
