### PR TITLE
pollo.eth

### PR DESCRIPTION
**Pull request by t0131murofushi**
Add
logo.png
spac.png

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Comment by gokaiorg** [comment]
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/pollo.eth

**Comment by t0131murofushi** [comment]
> I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/pollo.eth

Could you tell me this ?  "ou have filled in all required fields and added a strategy"
You mean that fill Settings form (https://snapshot.org/#/pollo.eth/settings)?
After I filled almost all fields,but "Save button"  is not change to clickable,is  there any reason?

**Comment by gokaiorg** [comment]
> Could you tell me this ? "ou have filled in all required fields and added a strategy"
> You mean that fill Settings form (https://snapshot.org/#/pollo.eth/settings)?
> After I filled almost all fields,but "Save button" is not change to clickable,is there any reason?

Yes, and did you add strategy here with a valid token? You can try with default DAI strategy to see if it's working.
https://docs.snapshot.org/spaces/create#strategies

**Comment by t0131murofushi** [comment]
> I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/pollo.eth

Thank you for your advice, I was able to create a space. Please complete my pull request. We apologize for the inconvenience, but thank you.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
