### PR TITLE
blockzerolabs.eth

### PR DESCRIPTION
**Pull request by KupoSteve**
#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Comment by gokaiorg** [comment]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

**Comment by KupoSteve** [comment]
> There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

I have updated the domains.json file to be up to date with the current master, but has also added our domain to it

**Comment by gokaiorg** [comment]
> I have updated the domains.json file to be up to date with the current master, but has also added our domain to it

To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Comment by KupoSteve** [comment]
> To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.

Thanks for the git commands help, I'm new to git. Does this look good to merge now?

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
