### PR TITLE
cryptopugz

### PR DESCRIPTION
**Pull request by Blockchaindevelopment01**
#### Hi! What is your PR about?

- [ y] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

### CODE REVIEW

**Comment by Blockchaindevelopment01** [comment]
My apologizes for all the changes I've forked projects but this is my first time doing a Pull request on github.

**Review by gokaiorg — CHANGES_REQUESTED** [review]
You should not change the name of this file but rather add your skin name to it.

**Review by gokaiorg — APPROVED** [review]

**Comment by samuveth** [comment]
@gokaiorg the file name was still changed. I can not merge this into the frontend like this.

**Comment by gokaiorg** [comment]
> @gokaiorg the file name was still changed. I can not merge this into the frontend like this. image

@samuveth Does this PR resolved this? https://github.com/snapshot-labs/snapshot-spaces/pull/1868

**Pull request merged**
