### PR TITLE
Add snapshot.puul.eth

### PR DESCRIPTION
**Pull request by puul-finance**
**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Review by gokaiorg — COMMENTED** [review]
I cannot find your space. Does it will be `snapshot.puul.eth` or `puul.eth`? Your space path should correspond with that name.

**Comment by puul-finance** [comment]
I added it as snapshot.puul.eth. I added the ipns to the domain and filled in the other fields. When I click Save, it asks me to sign a request, which I do. It then shows the loading spinner on the Save button, but it never stops.

**Comment by puul-finance** [comment]
As far as I can tell, it's there as snapshot.puul.eth. If I go to the home page and enter 'snapshot.puul.eth' it takes me to the settings page which looks correct.

**Comment by puul-finance** [comment]
It looks like your server was down. I just saved it and it seemed to work, so should be good to go.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
