### PR TITLE
fix nav

### PR DESCRIPTION
**Pull request by brennanfife**
**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Comment by brennanfife** [comment]
I believe the snapshot top nav has changed to our projects colors (pink)... Here is a quick fix...

**Comment by gokaiorg** [comment]
@brennanfife I have merged by mistake a pink navbar border, i will remove it, do you want to keep your new border or close this PR?

**Comment by brennanfife** [comment]
@gokaiorg I would like to add the skin + pink border (but obviously not conflict with the site's border)

**Comment by brennanfife** [comment]
Our project's image seems to be missing too

**Comment by gokaiorg** [comment]
@brennanfife Maybe you should close this PR, update your local environment and create a new PR. Thank you and sorry!

**Pull request closed without merging**
