### PR TITLE
Update new domain

### PR DESCRIPTION
**Pull request by drpaulitoc**
"vote.pokerkingsclub.com": "pokerkingsclub.eth",

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

### CODE REVIEW

**Comment by drpaulitoc** [comment]
Thank you for add domain

**Review by gokaiorg — CHANGES_REQUESTED** [review]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Your commit will delete several lines, can you fix that?

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
