### PR TITLE
Adding Protekt logo and space pngs

### PR DESCRIPTION
**Pull request by johnx25bd**
Hey Snapshot - hope this is right, I wasn't certain if I had to include the `.eth` in the `/spaces/*` directory name - if I so let me know, will fix it. 🙏 🛡️

### CODE REVIEW

**Comment by gokaiorg** [comment]
@johnx25bd Yes you should rename your space directory with your ENS. I cannot find a proteck.eth space, did you create it already?

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.

**Review by johnx25bd — COMMENTED** [review]
Updated as requested.

**Review by gokaiorg — CHANGES_REQUESTED** [review]
@johnx25bd I can't find your space yet https://snapshot.page/#/protekt.eth

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
