### PR TITLE
Add ENS for Pickle space

### PR DESCRIPTION
**Pull request by mannyreimi88**
#### Hi! What is your PR about?

Migrating the Pickle space to ENS.

- [ ] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/pickle.eth

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
[Pickle space migration](https://trello.com/c/nc1k8bRw/80-pickle-space-migration)

**Comment by mannyreimi88** [comment]
>  [Pickle space migration](https://trello.com/c/nc1k8bRw/80-pickle-space-migration)

@mannyreimi88 am I meant to get access? My email is `mannyreimi@gmail.com`

**Comment by bonustrack** [comment]
@mannyreimi88 Hey no, this is not publicly accessible, but i confirm that the space been successfully migrated. Let us know if you need anything.

**Pull request merged**
