### PR TITLE
Add pagedao.eth to domains.json

### PR DESCRIPTION
**Pull request by wipphil**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
There is a conflict in your PR since the `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by wipphil** [comment]
I moved my update above the last line. Please review my latest commit https://github.com/snapshot-labs/snapshot-spaces/pull/1804/commits/4e8f87641a640d6d80560df87bb039a0b3e6a13d

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
