### PR TITLE
Add PAPER space

### PR DESCRIPTION
**Pull request by flushlol**

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)
The images file size should not exceed 50KB. Please reduce their weight.

**Comment by flushlol** [comment]
So we can't use our own gov.flush.lol domain in the ENS version. So can we try the old way of creating space?

**Comment by bonustrack** [comment]
@flushlol You can have a custom domain for your space with ENS. You will need to add the domain in the domains.json file see here: https://docs.snapshot.page/guides/custom-domain

**Comment by flushlol** [comment]
@bonustrack thank you, I get it

**Pull request closed without merging**
