### PR TITLE
Add new logo, custom domain, and new skin.

### PR DESCRIPTION
**Pull request by imsuperleague**
#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add a custom domain for your space
- [ ] Add an alias for migrating your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
There is a conflict in your PR, can you resolve it?

**Comment by imsuperleague** [comment]
Can you help me? I tried to fix it but I couldn't. I just need to be able to use the skin and swap the new logo and space.

**Comment by gokaiorg** [comment]
> Can you help me? I tried to fix it but I couldn't. I just need to be able to use the skin and swap the new logo and space.

@imsuperleague To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Comment by imsuperleague** [comment]
I think it's done.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
