### PR TITLE
Added DRC Digital Reserve Currency Alias to ENS

### PR DESCRIPTION
**Pull request by Cryptographr**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add custom domain for your space
- [X] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy.
https://snapshot.org/#/drctoken.eth

**Comment by Cryptographr** [comment]
> I can't find your new space. Please make sure that you have filled in all required fields and added a strategy.
> https://snapshot.org/#/drctoken.eth

We are trying to migrate from legacy to the new Snapshot setup that needs an ENS.

Can you please commit this to the alias.json:  "digital-reserve-currency": "drctoken.eth"

Then I should be able to access areas to add new strategies?

**Comment by Cryptographr** [comment]
Reason for this PR is to: **Add alias for migrate your space**

**Comment by Cryptographr** [comment]
> I can't find your new space. Please make sure that you have filled in all required fields and added a strategy.
> https://snapshot.org/#/drctoken.eth

You should be able to see it now. Are you able to help with the Migration from the old to new?

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
