### PR TITLE
Add Stimmy Logo & Space

### PR DESCRIPTION
**Pull request by Stimmyio**
#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Your space name directory should be similar to your ENS and can't contain uppercase. Follow this example `spaces/stimmyio.eth/logo.png`.

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Your images are now missing.

**Comment by Stimmyio** [comment]
Images uploaded https://github.com/Stimmyio/snapshot-spaces/commit/30022f8054dd2e0240746ab8742adc277b0c34cc

**Comment by Stimmyio** [comment]
Images are uploaded.

**Comment by gokaiorg** [comment]
@Stimmyio Sorry i still can't see images in your PR. https://github.com/snapshot-labs/snapshot-spaces/pull/974/files

Could you follow this documentation? https://docs.snapshot.org/spaces/add-avatar

**Comment by Stimmyio** [comment]
Did that, I see the images right here. 

https://github.com/Stimmyio/snapshot-spaces/blob/master/spaces/stimmyio.eth/logo.png

**Comment by Stimmyio** [comment]
I think we've got it now, thanks for your patience.

**Pull request closed without merging**
