### PR TITLE
make default tab core in index.json

### PR DESCRIPTION
**Pull request by changmyeong**
make default tab core in index.json

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.
We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.
image

**Comment by changmyeong** [comment]
@gokaiorg 

it's not update images PR.
We currently have the "all" tab by default and would like to change this to "core".

**Comment by gokaiorg** [comment]
@changmyeong It is no longer possible to modify this file. The only configurations you can change are those located in the settings of your space.

**Comment by changmyeong** [comment]
@gokaiorg 
How do I change the default tab to "core" ?
I didn't find any changes to the default tabs in the space settings.

**Comment by changmyeong** [comment]
@gokaiorg Oh, Sorry. I found it.

**Pull request closed without merging**
