### PR TITLE
Update domains.json

### PR DESCRIPTION
**Pull request by rizedr**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

### CODE REVIEW

**Review by gokaiorg — APPROVED** [review]

**Comment by mihneadb** [comment]
@gokaiorg hey, we set up the CNAME as well and noticed that vote.stakeborgdao.com takes you to the Snapshot homepage, and not to the space itself (https://snapshot.org/#/stakeborgdao.eth). 
Already called https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=stakeborgdao.eth but saw `Requesting new SSL failed - domain might not be pointed correctly.`
Is there anything else we need to do, or just wait for stuff to propagate?

Thanks!

**Comment by gokaiorg** [comment]
@mihneadb You need to add your sub domain here https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=vote.stakeborgdao.com

Then it should be related to your DNS config https://docs.snapshot.org/spaces/add-custom-domain#configure-your-dns
Did you do this step? `You will need to add this as CNAME in your domain DNS snapshotpage.b-cdn.net`

**Comment by mihneadb** [comment]
@gokaiorg I did nothing since posting my message and now it works :) maybe something took more time to happen? Thanks!

**Comment by mihneadb** [comment]
And yes, I did do the CNAME and all steps for that matter.

**Pull request merged**
