### PR TITLE
Update cream space

### PR DESCRIPTION
**Pull request by jeremyHD**
**This PR should be merged after https://github.com/snapshot-labs/snapshot.js/pull/22**  

Update strategy for cream space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Your changes will cause an error and your space will no longer load properly.
@bonustrack If you could review those strategies. Thank you.

**Comment by jeremyHD** [comment]
Yup, this change will work properly only after https://github.com/snapshot-labs/snapshot.js/pull/22 this is merged

**Comment by gokaiorg** [comment]
We've made a major global update, it will be necessary to update `index.json` with the master branch before merge.
You can use the documentation to help you.
https://docs.snapshot.page/guides/create-a-space#1-fork-snapshot-spaces-repository-here

**Comment by jeremyHD** [comment]
@gokaiorg PR updated :)

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
