### PR TITLE
adds pleasrDAO logo

### PR DESCRIPTION
**Pull request by jamiis**
#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/pleasrdao.eth

**Comment by jamiis** [comment]
hi @gokaiorg, I've tried ~10 times over the past 24 hours to add a space. I fill in all of Profile, choose the Strategy with updated token name and contract, and also fill in members. I do not do Filter or Plugins. I am quite sure I have all the required fields because sometimes the Save button turns blue, but when I press it it just perma-hangs on processing. Other times after I've filled out the fields the Save button still isn't active. Igor in TG kindly let me know to wait a few hours and try again but I've been trying since last night. Are you aware of any weird issues with the current deploy of Snapshot? Could it be a weird Gnosis Safe multi sig issue? says I connected as pleasrdao.eth through Wallet Connect on Gnosis Safe but not sure if that's adequate. Thanks for any help

**Comment by gokaiorg** [comment]
> hi @gokaiorg, I've tried ~10 times over the past 24 hours to add a space. I fill in all of Profile, choose the Strategy with updated token name and contract, and also fill in members. I do not do Filter or Plugins. I am quite sure I have all the required fields because sometimes the Save button turns blue, but when I press it it just perma-hangs on processing. Other times after I've filled out the fields the Save button still isn't active. Igor in TG kindly let me know to wait a few hours and try again but I've been trying since last night. Are you aware of any weird issues with the current deploy of Snapshot? Could it be a weird Gnosis Safe multi sig issue? says I connected as pleasrdao.eth through Wallet Connect on Gnosis Safe but not sure if that's adequate. Thanks for any help

@jamiis There is a problem with the signature message of Gnosis Safe. It does not work at the moment.

**Comment by jamiis** [comment]
@gokaiorg thank you for your help on telegram! we have finished setting up a Space

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
