### PR TITLE
add to domainsjs and aliasesjson

### PR DESCRIPTION
**Pull request by rayconnection**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [x] Add an alias to migrate your space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
When creating a space you do not have to edit the `aliases.json` file.

**Comment by rayconnection** [comment]
Sorry, I didnt understand. Here you ask that is possible: https://docs.snapshot.org/spaces/migrate#2.-declare-your-new-space-alias

**Comment by rayconnection** [comment]
> Sorry, I didnt understand. Here you ask that is possible: https://docs.snapshot.org/spaces/migrate#2.-declare-your-new-space-alias

Sorry, I didnt understand. Here you ask that is possible: https://docs.snapshot.org/spaces/migrate#2.-declare-your-new-space-alias

**Comment by rayconnection** [comment]
> When creating a space you do not have to edit the `aliases.json` file.

Sorry, I didnt understand. Here you ask that is possible: https://docs.snapshot.org/spaces/migrate#2.-declare-your-new-space-alias

**Pull request closed without merging**
