### PR TITLE
Update domains.json

### PR DESCRIPTION
**Pull request by chorusg**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [+] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
You will need to update your `domains.json` file on your local before you commit again.

**Comment by chorusg** [comment]
Hi, we updated it at line 51.
 "vote.xtblock.io": "xtblock.eth",

https://github.com/xtblock/snapshot-spaces/blob/master/spaces/domains.json

**Comment by gokaiorg** [comment]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

**Comment by chorusg** [comment]
https://github.com/xtblock/snapshot-spaces/blob/master/spaces/domains.json

We have just downloaded the latest domains.json file and updated it at line 60.

**Comment by gokaiorg** [comment]
@chorusg Please have a look here https://github.com/snapshot-labs/snapshot-spaces/pull/1526/files just your line should be modified.

**Pull request closed without merging**
