### PR TITLE
migrate x7finance

### PR DESCRIPTION
**Pull request by Adz1DoubleD**
[X] Add an alias to migrate your space

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
No proposals to migrate on https://snapshot.org/#/x7community.eth or on new space. refer to https://docs.snapshot.org/user-guides/spaces/migrate-or-delete#migrate-a-space

**Comment by Adz1DoubleD** [comment]
https://snapshot.org/#/x7community.eth/proposal/0x8221539cf3c329ee654f673584e7e37b665107af345bc7b6e3ca512f90c89064
 https://snapshot.org/#/x7finance.eth/proposal/0x1b18e8797267995ace6fd9895b159992ac4cd2028e3135652880ba4128eaa7f0

**Comment by Adz1DoubleD** [comment]
@ChaituVR see above comments

**Comment by ChaituVR** [comment]
Thanks, @Adz1DoubleD I have initiated the process. it may take some time. will let you know once it is done

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
Migration is completed @Adz1DoubleD

**Pull request merged**
