### PR TITLE
Smaller truegov eth logo

### PR DESCRIPTION
**Pull request by dannyrdalton**
#### Hi! What is your PR about?

- [x] Update images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — APPROVED** [review]
Your space doesn't seems to load properly. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/truegov.eth

**Comment by subhajit-trusttoken** [comment]
Hi @gokaiorg the link to our space is https://snapshot.org/#/truefigov.eth

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Your space name directory should be similar to your ENS. Follow this example `spaces/truefigov.eth/logo.png`.

**Comment by dannyrdalton** [comment]
Ah, I wasn't aware of the change on our end. PR updated to `spaces/truefigov.eth`

**Comment by dannyrdalton** [comment]
aye aye aye, introduced a conflict somehow

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
@dannyrdalton Could you resolve this conflit?

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
