### PR TITLE
add okcashlab.eth

### PR DESCRIPTION
**Pull request by okcashlab**
update the pull request and delete the index.js

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Comment by gokaiorg** [comment]
Do you have access to this page and if so, did you fill in the required fields? https://snapshot.page/#/okcashlab.eth/settings

**Comment by okcashlab** [comment]
> Do you have access to this page and if so, did you fill in the required fields? https://snapshot.page/#/okcashlab.eth/settings

Yeah, I have finished it

**Comment by gokaiorg** [comment]
You can still try to edit and save your changes and wait a few minutes. Make sure to clear your browser caches.

**Comment by okcashlab** [comment]
> You can still try to edit and save your changes and wait a few minutes. Make sure to clear your browser caches.

Hey, In the settings page, I can’t click save, why?

**Comment by okcashlab** [comment]
> You can still try to edit and save your changes and wait a few minutes. Make sure to clear your browser caches.

Hi, I have reset the settings page, please check

**Pull request closed without merging**
