### PR TITLE
add basisgold.eth space

### PR DESCRIPTION
**Pull request by basisgold**
add basisgold.eth space

### CODE REVIEW

**Review by basisgold — COMMENTED** [review]
review

**Comment by basisgold** [comment]
finish review and add basisgold.eth space

**Review by basisgold — COMMENTED** [review]
review

**Review by gokaiorg — CHANGES_REQUESTED** [review]
The images file size should not exceed 50KB. Please reduce their weight.

**Comment by gokaiorg** [comment]
> The images file size should not exceed 50KB. Please reduce their weight.

And should be squared format.

**Review by basisgold — COMMENTED** [review]
Change the images file size and 180*180

**Comment by basisgold** [comment]
please check it,   thank you

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
