### PR TITLE
DEXTF material

### PR DESCRIPTION
**Pull request by dextfprotocol**
Added images, skin, custom domain

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Comment by gokaiorg** [comment]
I cannot find your https://snapshot.page/#/dextfprotocol.eth space, did you creates it already?

**Comment by dextfprotocol** [comment]
Yes I did, it’s still empty (see screenshot).
PastedGraphic-1

**Comment by gokaiorg** [comment]
You may miss some settings.

**Comment by gokaiorg** [comment]
You can still try to edit and save your changes and wait a few minutes. Make sure to clear your browser caches.

**Comment by dextfprotocol** [comment]
Whatever change I do in the dextfprotocol.eth snapshot's Profile settings (Name, Network, etc...) the Save button is disabled (see screenshot).

settings

Note that I have connected my wallet that is the ENS Controller (not the Registrant). Could that be the problem?

**Comment by gokaiorg** [comment]
@dextfprotocol Did you add a strategy?

**Comment by dextfprotocol** [comment]
Ok, apparently I had to add a strategy and "magically" the Save button became enabled. I have not set the fields under Profile (Name, Network, etc...). The space is now visible. Could you proceed with the review/merge of this pull request?

**Comment by gokaiorg** [comment]
@dextfprotocol Very nice, the `domains.json` has been updated and there is now a conflict, could you update it?

**Comment by dextfprotocol** [comment]
I've updated domains.json based on the latest version

**Comment by gokaiorg** [comment]
The conflict is not resolved, you need to update your fork with the snapshot-spaces master branch. Something like this should work:
`git remote add master https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch master`
`git checkout master`
`git merge master/master`

**Comment by dextfprotocol** [comment]
what about now?

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
