### PR TITLE
add vote.coniun.io

### PR DESCRIPTION
**Pull request by BatuhanK**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

We added `vote.coniun.io`

### CODE REVIEW

**Comment by gokaiorg** [comment]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by BatuhanK** [comment]
@gokaiorg resolved, can you merge?

**Comment by gokaiorg** [comment]
@BatuhanK Sorry, here we go again, the domain.json file has just been updated, please ping me when it's done!

**Comment by BatuhanK** [comment]
@gokaiorg just fixed again; can we merge :(

**Comment by BatuhanK** [comment]
@gokaiorg sorry for ping, but our community waits a domain which belongs to us join. can you merge if it's ok?

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
