### PR TITLE
add invalid proposal id in filters to remove the test proposals

### PR DESCRIPTION
**Pull request by Jeffqg123**
add invalid proposal id in filters to remove the test proposals

### CODE REVIEW

**Comment by gokaiorg** [comment]
If you change the base token address your old proposals will not be visible anymore under your space. It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

**Comment by Jeffqg123** [comment]
You mean I need to change this address?
"strategies": [
    {
      "name": "contract-call",
      "params": {
        "address": "0x3f5014e49e03d4444483662cc70618cd8087f9d2",
        "decimals": 18,
        "symbol": "fnx",
        "methodABI": {
          "constant": true,
          "inputs": [
            {
              "internalType": "address",
              "name": "_user",
              "type": "address"
            }
          ],
          "name": "fnxBalanceAll",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "payable": false,
          "stateMutability": "view",
          "type": "function"
        }
      }
    }
  ]

**Comment by gokaiorg** [comment]
@Jeffqg123 I mean, since you're going to transform the strategy of your space so that you won't have any more proposals, as if you had a new space, you'll have to recreate a space with the ENS method instead.

**Comment by Jeffqg123** [comment]
If I recreate a new space for FinNexus, the the new space will replace the old one? and the new space can use same space  name for FinNexus?

**Comment by gokaiorg** [comment]
You can keep your older space or migrate it following documentation https://docs.snapshot.page/guides/migrate-your-space-to-ens

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
