### PR TITLE
buger.eth

### PR DESCRIPTION
**Pull request by GAOXING-OK**
#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Comment by gokaiorg** [comment]
- Your images are missing from you PR. 
- Your space name directory `空格/buger.eth` should be similar to your ENS. Follow this example `spaces/buger.eth/logo.png`.

**Review by GAOXING-OK — COMMENTED** [review]
OK

**Review by gokaiorg — CHANGES_REQUESTED** [review]
Please remove the `32X32.png` image.

**Comment by gokaiorg** [comment]
Done in #1200

**Pull request closed without merging**
