### PR TITLE
add vote.samoswap.com domain

### PR DESCRIPTION
**Pull request by x0archie**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [X] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
- There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
- We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.

image

**Comment by devsamo** [comment]
updated domain,json, and the logo has been deleted, I will add via UI, thanks

**Comment by gokaiorg** [comment]
> updated domain,json, and the logo has been deleted, I will add via UI, thanks

@devsamo Sorry the conflict still there, could you do it again please? Thanks

**Comment by gokaiorg** [comment]
To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Comment by devsamo** [comment]
ok done

**Comment by gokaiorg** [comment]
> To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
> `git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
> `git fetch upstream`
> `git checkout master`
> `git merge upstream/master`

@devsamo Could you please follow this steps to try to update domains.json file?

**Comment by x0archie** [comment]
hi, i have done with the commands, kindly recheck

**Comment by gokaiorg** [comment]
> hi, i have done with the commands, kindly recheck

@x0archie Hi! It doesn't work any better. If you can't update I recommend you to close this PR and start from a new fork.

**Comment by x0archie** [comment]
oh ok... thanks anyway for your support

**Pull request closed without merging**
