### PR TITLE
Add Skin and Logo for Benchmark Protocol

### PR DESCRIPTION
**Pull request by meirbank**

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
image

**Comment by meirbank** [comment]
> The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
> image

My bad, thanks for pointing that out. Updated the primary color

**Comment by gokaiorg** [comment]
@meirbank I see the same green button with the unreadable label, you should play with border and link color to make it visible.

**Comment by meirbank** [comment]
Ok I think the issue was link color should be white from what I've seen on other skins. Sorry about that.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
