### PR TITLE
Add Origin skin

### PR DESCRIPTION
**Pull request by micahalcorn**
#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

Adds the Origin skin to be used at [origingov.eth](https://snapshot.box/#/s:origingov.eth) 💙

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi @micahalcorn Skins are not supported on snapshot.box yet, you plan to use this on V1 (snapshot.org)?

**Comment by micahalcorn** [comment]
> Hi @micahalcorn Skins are not supported on snapshot.box yet, you plan to use this on V1 (snapshot.org)?

Oh, thanks, I was confused. I thought skins were a new feature with the box interface. We're happy to try it out on the old version for now.

**Comment by ChaituVR** [comment]
I see 😄 you need to add a custom domain to the skin https://docs.snapshot.org/user-guides/spaces/add-custom-domain

**Comment by micahalcorn** [comment]
> I see 😄 you need to add a custom domain to the skin https://docs.snapshot.org/user-guides/spaces/add-custom-domain

Okay, we already had a custom domain but I've updated it in this PR. Let me know if I can do anything else.

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
