### PR TITLE
update red.che.eth linked domain url

### PR DESCRIPTION
**Pull request by redblow**
dao.decentrastates.org => vote.decentrastates.org

### CODE REVIEW

**Comment by gokaiorg** [comment]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by Decentrastates** [comment]
yes, I have change domain, and use new domain vote.decentrastates.org.

**Comment by gokaiorg** [comment]
To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Review by faves4less — APPROVED** [review]

**Review by faves4less — APPROVED** [review]

**Review by faves4less — APPROVED** [review]

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
