### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MrCuddleMuffin**
#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- [x] Edit your space with GitHub? It's recommended to migrate to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Comment by MrCuddleMuffin** [comment]
Let me just apologize ahead of time if I screwed this up somehow my first time trying to merge a fork or file with an existing git repository tried using git bash but didnt have the best of luck I tried following all instruction laid out in the docs and faq and such but I wont lie a lot of it was not working for me whenever entering the command line prompts for git bash to push the request

**Review by gokaiorg — CHANGES_REQUESTED** [review]
- You space directory must be in the `spaces` directory.
- Rename your images from `logo.png.png` to `logo.png`.
- Your space name directory should be similar to your ENS. Follow this example `spaces/diamondhandsfinance.eth/logo.png`.

https://snapshot.page/#/diamondhandsfinance.eth

**Comment by gokaiorg** [comment]
> Let me just apologize ahead of time if I screwed this up somehow my first time trying to merge a fork or file with an existing git repository tried using git bash but didnt have the best of luck I tried following all instruction laid out in the docs and faq and such but I wont lie a lot of it was not working for me whenever entering the command line prompts for git bash to push the request

To update your fork you try this commands:
`git remote add master https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch master`
`git checkout master`
`git merge master/master`

**Comment by MrCuddleMuffin** [comment]
So I think sent all the right stuff in and did my strategy go through??

**Comment by gokaiorg** [comment]
> So I think sent all the right stuff in and did my strategy go through??

Your strategy looks good to me https://hub.snapshot.page/api/spaces/diamondhandsfinance.eth

Your space name directory and your images still not good!

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
