### PR TITLE
Add Meter spaces

### PR DESCRIPTION
**Pull request by xiaohanzhu**
Two spaces included.  One for Meter mainnet and the other for wrapped ETH version
**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
You should remove index.json form your PR.

**Comment by xiaohanzhu** [comment]
How do I specify different strategy and network without the index.json file?

**Comment by bonustrack** [comment]
@xiaohanzhu From the interface you can setup a space using ENS and have a custom network and strategie(s), have a look here: https://docs.snapshot.page/guides/create-a-space

**Comment by xiaohanzhu** [comment]
The ENS create space only mentioned adding logos for the strategies.  https://docs.snapshot.page/strategies  talked about configuring strategies and network in the index.json file.  However @gokaiorg asked me to remove index.json  How do I configure different strategies and network without index.json?

**Comment by bonustrack** [comment]
@xiaohanzhu Once your ENS space is setup, you will be able to edit the network and strategies within the settings page, see: 
image

**Comment by xiaohanzhu** [comment]
Could you please check if these changes are OK?

**Review by gokaiorg — APPROVED** [review]
@xiaohanzhu I cannot find the meter-mainnet.eth space, did you create it already?

**Comment by xiaohanzhu** [comment]
yes, it was created already.  The attached is the settings page.  Does the multicall to our rpc end point have to succeed for the proposal page to show up? #
Screen Shot 2020-12-01 at 7 29 05 PM

**Comment by gokaiorg** [comment]
@xiaohanzhu I let Fabien answer this question on Discord Helpdesk channel.

**Pull request merged**
