### PR TITLE
Update Contract Information

### PR DESCRIPTION
**Pull request by hurricanefinance**
- Update final symbol
- Update final HUGO contract address

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

**Comment by hurricanefinance** [comment]
Hey, our space already exists.

I was just editing the network, symbol and token address in the config. 

Can we please just get that in?

**Comment by gokaiorg** [comment]
@hurricanefinance I see you don't have any proposal yet, we update only spaces contains proposals and invite others to migrate to ENS then you won't need anymore to PR to update your space.
Could you have a look on this doc and try to migrate?
https://docs.snapshot.page/guides/migrate-your-space-to-ens

**Comment by hurricanefinance** [comment]
Yea, we are right in the middle of launch today and are pretty swamped. That's the only reason I asked if we can just have this single file updated vs having to go through the process again, this time with ENS and etc.

I would greatly appreciate if you could. Otherwise, I will have to get back to this maybe next week once our launch dust has settled.

Thanks

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
Ok done.

**Comment by hurricanefinance** [comment]
Wow - thank you so much! I really appreciate it!

**Pull request merged**
