### PR TITLE
updated balanceOf target to new DHT staking contract

### PR DESCRIPTION
**Pull request by radek1st**

### CODE REVIEW

**Review by gokaiorg — APPROVED** [review]
- If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?
- It's now possible to edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to migrate your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space

**Comment by radek1st** [comment]
Thanks @gokaiorg 
I've set up the eth domain, can I just rename this space to gov.dhedge.eth ?

**Comment by gokaiorg** [comment]
> Thanks @gokaiorg 
> I've set up the eth domain, can I just rename this space to gov.dhedge.eth ?

@radek1st firstly make sure your https://snapshot.page/#/gov.dhedge.eth space is loading properly, you have to fill all required fields and you need to add a strategy in your settings page.
Then add an alias following this doc https://snapshot.page/#/gov.dhedge.eth
So you will be able to modify this space and we will complete your migration! Thank you.

**Comment by radek1st** [comment]
ok, new snapshot page is looking good, I guess I'll have to rename the skin from dhedge to gov.dhedge.eth in settings once merged

**Comment by gokaiorg** [comment]
> ok, new snapshot page is looking good, I guess I'll have to rename the skin from dhedge to gov.dhedge.eth in settings once merged

Your skin can keep the same name, but you have to delete the index.json file because all the configurations are done via your settings page.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
