### PR TITLE
Add stkGRO space

### PR DESCRIPTION
**Pull request by Mohsen-T**
Changing token name on the UI

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

**Comment by Mohsen-T** [comment]
Would it be possible for you to just merge it for now? Hopefully I can do that from the next update.

**Review by gokaiorg — COMMENTED** [review]
If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've take a final decision.

**Pull request closed without merging**
