### PR TITLE
chore: Spectra DAO custom domain

### PR DESCRIPTION
**Pull request by matstyler**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

### CODE REVIEW

**Comment by wa0x6e** [comment]
Please also complete steps 4 to 6 from the docs https://docs.snapshot.org/user-guides/spaces/add-custom-domain#2.-add-your-custom-domain-to-domains.json

**Comment by matstyler** [comment]
> Please also complete steps 4 to 6 from the docs https://docs.snapshot.org/user-guides/spaces/add-custom-domain#2.-add-your-custom-domain-to-domains.json

This PR looks like step 6. About step 4 - it's done as well.

**Comment by wa0x6e** [comment]
> > Please also complete steps 4 to 6 from the docs https://docs.snapshot.org/user-guides/spaces/add-custom-domain#2.-add-your-custom-domain-to-domains.json
> 
> This PR looks like step 6. About step 4 - it's done as well.

The doc has just been updated, and steps order have changed.

Can you ensure you have completed all the steps ? The domain http://vote.spectra.finance/ is not redirecting to snapshot yet

**Comment by matstyler** [comment]
> > > Please also complete steps 4 to 6 from the docs https://docs.snapshot.org/user-guides/spaces/add-custom-domain#2.-add-your-custom-domain-to-domains.json
> > 
> > 
> > This PR looks like step 6. About step 4 - it's done as well.
> 
> The doc has just been updated, and steps order have changed.
> 
> Can you ensure you have completed all the steps ? The domain http://vote.spectra.finance/ is not redirecting to snapshot yet

I see. It should be fine now.

**Comment by matstyler** [comment]
> Can you update your space settings with the custom domain name ? https://snapshot.org/#/spectradao.eth/settings

Done

**Pull request merged**
