### PR TITLE
Update aliases.json

### PR DESCRIPTION
**Pull request by LucaSilverhand**
#### Hi! What is your PR about?

- [1] Add levinswap.eth to Snapshopt
- [2 ] Adding Levin image
- [ 3] Adding custom domain to our space

### CODE REVIEW

**Comment by gokaiorg** [comment]
There is a conflict in your PR, can you resolve it?

**Comment by gokaiorg** [comment]
I think you are doing a space creation and not a space migration, you may not need to edit `aliases.json`

**Comment by LucaSilverhand** [comment]
If I understand correctly, I've created new space via UI on Snapshot and now I need to migrate existing space?

**Comment by gokaiorg** [comment]
> If I understand correctly, I've created new space via UI on Snapshot and now I need to migrate existing space?

Do you have an existing space? If so can you give me the url?

**Comment by LucaSilverhand** [comment]
> > If I understand correctly, I've created new space via UI on Snapshot and now I need to migrate existing space?
> 
> Do you have an existing space? If so can you give me the url?

Yes we do - https://snapshot.org/#/levinswap.eth

**Comment by gokaiorg** [comment]
> Yes we do - https://snapshot.org/#/levinswap.eth

This is your new space, you don't need to edit the aliases file.
You can, however, add images https://docs.snapshot.org/spaces/add-avatar or a subdomain https://docs.snapshot.org/spaces/add-custom-domain.
I'm closing this PR for now, feel free to reopen it if you want to add elements or open another one.

**Pull request closed without merging**
