### PR TITLE
Add mvb eth

### PR DESCRIPTION
**Pull request by PicksLabs**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

I need to add "irldao.co": "irldao.eth" to domains.json

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
There is a conflict in your PR since the `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by PicksLabs** [comment]
How do I resolve this? Can you send me an example please?

**Comment by gokaiorg** [comment]
To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
