### PR TITLE
PR - New Logo, Cosmetic Edits, Invalid Proposal

### PR DESCRIPTION
**Pull request by CryptoBiased**
PR - New Logo, Cosmetic Edits, Invalid Proposal

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
image

**Comment by CryptoBiased** [comment]
Done!

**Comment by CryptoBiased** [comment]
hi!  did i miss something?  change was made to address font legibility

**Comment by CryptoBiased** [comment]
Not sure what is taking so long, so I will cancel and try again.

**Pull request closed without merging**
