### PR TITLE
Ethereum4 Snapshot Space

### PR DESCRIPTION
**Pull request by Matlemad**
#### Hi! What is your PR about?
Ethereum4 is an educational project intended at addressing different indutries' interest groups and exploring together the WEB3 solutions offered by the Ethereum blockchain

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Comment by gokaiorg** [comment]
@Matlemad  You have a similar problem in this PR, your images are not added correctly.

**Comment by Matlemad** [comment]
@gokaiorg now?

**Comment by gokaiorg** [comment]
> @gokaiorg now?

@Matlemad Yes it's good, just your space name directory should be similar to your ENS. Follow this example `spaces/ethereum4.eth/logo.png`.

**Comment by Matlemad** [comment]
@gokaiorg ok done it! please confirm :)

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
@Matlemad You should add a `logo.png` image in addition to your `space.png` image, do you want to do it now?

**Comment by Matlemad** [comment]
@gokaiorg oh alright. logo.png added (same img as space.png) :)

**Pull request merged**
