### PR TITLE
Updates domains.json to add Vote.Skullz.City

### PR DESCRIPTION
**Pull request by MadGraph**
#### Hi! What is your PR about?

- [x] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
To create your skin will also need to list your skin in this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

**Comment by MadGraph** [comment]
Thank you!
Will edit that asap and submit the PR again

Best
M.

**Comment by MadGraph** [comment]
> To create your skin will also need to list your skin in this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

It is now done sir! Thanks for your time reviewing

**Review by gokaiorg — CHANGES_REQUESTED** [review]
You will also need to add your skin in the `export default {` table line 305 of `index.js file`. https://github.com/snapshot-labs/snapshot-spaces/blob/8d4de2a1db2e8e77539a7c9ca24a8bc8d4e14ecb/skins/index.js#L305

**Comment by MadGraph** [comment]
Now up to date :) Thank you

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
