### PR TITLE
柴图vr补丁2

### PR DESCRIPTION
**Pull request by 16183**
- [x] Add or edit a skin
- [x] Add custom domain for your space
- [x] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Comment by 16183** [comment]
1

**Comment by 16183** [comment]
https://github.com/snapshot-labs/snapshot-spaces/pull/1380/commits/631c2db8a7eb052b93ff6babf8fb29241fea4c03

**Comment by 16183** [comment]
ipns://storage.snapshot.page/registry/0x6121BDbFe5d3D43e49fDC516905aAF0Ea5069246/sswap.eth

**Comment by 16183** [comment]
ipns://storage.snapshot.page/registry/0x6121BDbFe5d3D43e49fDC516905aAF0Ea5069246/sswap.eth

**Review by gokaiorg — COMMENTED** [review]
We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.
image

**Pull request closed without merging**
