### PR TITLE
add dot.finance

### PR DESCRIPTION
**Pull request by or2008**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — COMMENTED** [review]
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/dotfinance.eth

**Comment by or2008** [comment]
Hi can you check now please? I believe it there now

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by or2008** [comment]
done

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
