### PR TITLE
update DANIMESQ-xdai space

### PR DESCRIPTION
**Pull request by DaniellMesquita**

### CODE REVIEW

**Comment by DaniellMesquita** [comment]
reference: https://github.com/snapshot-labs/snapshot-spaces/pull/390

**Review by gokaiorg — COMMENTED** [review]
- If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?
- It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

**Comment by gokaiorg** [comment]
@DaniellMesquita Do you validate your change, do you plan to migrate your spaces on ENS? Thank you

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
