### PR TITLE
Updated members in 'swarm' workspace

### PR DESCRIPTION
**Pull request by bowsernet**
**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

**Comment by bowsernet** [comment]
Hi, yeah, we could use the new method, but we realized only now that the swarm.eth was already taken. We had to rename our space to 'swarmnetwork' and I think this will have to go in as a pull request after all. Thanks and let me know in case this is not all right.

**Comment by gokaiorg** [comment]
Your space path should be similar to your ENS domain name, something like `spaces/swarmnetwork.eth/logo.png`. Do not commit again `index.json`. Keep this in your ENS parameters.

**Comment by bowsernet** [comment]
Changed directory name to swarmnetwork.eth and deleted index.json. Hope that's right

**Comment by gokaiorg** [comment]
@bowsernet Sorry but there is a confusion in your PR. I thought you were creating a new space when you are editing an existing one. 
In this PR you add 2 images in a new space and delete index.json from the existing space. 
We have to choose here whether you want to modify the `swarm' space or create the `swarmnetwork.eth' space.
Thank you.

**Comment by bowsernet** [comment]
Well, I admit I'm confused myself. We don't need the old space since we couldn't manage it through ENS (someone else owns swarm.eth). Should I keep it anyway? Does the new space need index.json then?

The PR as it is now renames the space from 'swarm' to 'swarmnetwork.eth' and deletes index.json because as I understand it, it's no longer needed. If this is wrong, what's the proper way to achieve what we need? Which is to have a new 'swarmnetwork.eth' space which we can manage ourselves and ideally remove the old one ('swarm')?

Sorry if I'm missing something and thanks!

**Pull request merged**
