### PR TITLE
Adding vote.hectordao.com

### PR DESCRIPTION
**Pull request by cwhittaker123**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ X] Add a custom domain for your space
- [ ] Add an alias to migrate your space

### CODE REVIEW

**Review by HectorDAO-HEC — APPROVED** [review]
It is correct we want to add the domain vote.hectordao.com as custom domain to our space.

**Review by gokaiorg — APPROVED** [review]

**Comment by gokaiorg** [comment]
There is a conflict in your PR since the `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by cwhittaker123** [comment]
> There is a conflict in your PR since the `domains.json` file has been updated, can you resolve it? To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

@gokaiorg Fixed the merge conflict. Can you please merge?

**Review by gokaiorg — APPROVED** [review]

**Comment by HectorDAO-HEC** [comment]
Hello @gokaiorg,

I believe we've set everything as we needed to set, but the new domain vote.hectordao.com is resolving to the mainpage of the snapshot domain.

Anything we need to change? Let us know please!

Thanks,

Zeus (HectorDAO)

**Pull request merged**
