### PR TITLE
Create blakeburrito.eth

### PR DESCRIPTION
**Pull request by blakeburrito**
#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- [ ] Edit your space with GitHub? It's recommended to migrate to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
It seems that you forgot to add your images in the PR. Can you add them? Thanks

**Comment by blakeburrito** [comment]
I’ll try to do that today. I had some trouble figuring out how to add a file to the new space. 

Could you possibly help?

Blake Sisk
816.398.1186
siskblake@gmail.com

**Comment by gokaiorg** [comment]
> I’ll try to do that today. I had some trouble figuring out how to add a file to the new space. Could you possibly help? 

1. Fork this repository https://github.com/snapshot-labs/snapshot-spaces
2. Clone the fork on your local machine
3. Create a directory `blakeburrito.eth` in the `spaces` directory following this doc https://docs.snapshot.page/spaces/add-avatar
4. Add your images inside, square format and less than 50kb
5. Configure the remote `git remote add upstream https://github.com/snapshot-labs/snapshot-spaces` https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
6. Add you new files `git add -A` 
7. Commit your new files `git push upstream master`
8. Follow the link in your terminal and create the Pull Request
9. Done, wait for review ;)

Hope could help you

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes. Let me know if you need more help.

**Pull request closed without merging**
