### PR TITLE
Update domains.json

### PR DESCRIPTION
**Pull request by PhanesNetwork**
#### Hi! What is your PR about?

- [x] Add or edit a skin
- [x] Add a custom domain for your space
- [x] Add an alias to migrate your space

### CODE REVIEW

**Comment by PhanesNetwork** [comment]
Add a custom domain for your space

**Comment by PhanesNetwork** [comment]
Add a custom domain for gov.phanes.network

**Comment by PhanesNetwork** [comment]
Adding a custom domain for gov.phanes.network

**Comment by wa0x6e** [comment]
Your custom domain ` gov.phanes.network` has an SSL issue

**Comment by PhanesNetwork** [comment]
Oh.. that's weird, what am I doing wrong here?
How do I get it fixed?

**Comment by wa0x6e** [comment]
> Oh.. that's weird, what am I doing wrong here? How do I get it fixed?

The certificate on your subdomain is not setup correctly, or setup at all

**Comment by PhanesNetwork** [comment]
It's set up, wildcat was use to set it up. But will have one last check just to verify.

**Comment by wa0x6e** [comment]
> It's set up, wildcat was use to set it up. But will have one last check just to verify.

Screenshot 2023-11-09 at 18 46 35

**Comment by PhanesNetwork** [comment]
We will fix this asap, thanks!

**Review by wa0x6e — APPROVED** [review]
utAck

**Pull request merged**
