### PR TITLE
add mind.eth

### PR DESCRIPTION
**Pull request by ottman**
**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
- I can't find your https://snapshot.page/#/mind.eth space, did you create it already?
- Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

**Comment by orishim** [comment]
@gokaiorg we filled out the form on the Create Space and but it failed to load when submitted. That is why we included the index.json. We can remove it and try resubmitting

**Comment by gokaiorg** [comment]
> @gokaiorg we filled out the form on the Create Space and but it failed to load when submitted. That is why we included the index.json. We can remove it and try resubmitting

Yes please try again, it should works!

**Comment by ottman** [comment]
This time metamask did prompt me to sign, but it is still stalled on the save button spinning.

**Comment by gokaiorg** [comment]
> This time metamask did prompt me to sign, but it is still stalled on the save button spinning.

@bonustrack Do you have an idea of what could happen here? thank you.

**Comment by bonustrack** [comment]
@ottman There was probably some downtime with the IPNS pinning service we are using. I just tried and it seem to work fine now can you try again to see if it's resolved?

**Comment by ottman** [comment]
I did it again and it seems to have allowed me to save. I saw a popup. Should it be showing on snapshot.page?

**Comment by gokaiorg** [comment]
Yes it's working now. Just delete index.json from your PR and you're done.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
