### PR TITLE
TOAST space updated

### PR DESCRIPTION
**Pull request by Cryptoastio**
We have changed a couple of things in our snapshot config.

### CODE REVIEW

**Review by e-asia — CHANGES_REQUESTED** [review]
We've made a major global update, please pull before commit again your changes. Thank you.

**Comment by Cryptoastio** [comment]
Should be fixed now

**Comment by gokaiorg** [comment]
> Should be fixed now

Maybe to much fixed, you are up to date with the master branch but have not committed any changes!

**Comment by Cryptoastio** [comment]
Oops! Try now

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
