### PR TITLE
Add Belugaswap space

### PR DESCRIPTION
**Pull request by chainvisions**
**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

**Comment by chainvisions** [comment]
Hi @gokaiorg, I do not have an ENS name so I cannot create a space using ENS which means I need to use Github instead.

**Comment by gokaiorg** [comment]
@chainvisions The migration to ENS is definitive, the objective is to have 100% of our spaces working with ENS and IPNS for the management of your data. 
This will allow users to edit their spaces on their own whenever they want without the need to create PR.
The process is easy and inexpensive, could you try to get an ENS? Thanks

**Comment by gokaiorg** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
