### PR TITLE
Updated GaiaDAO logo and added domain.

### PR DESCRIPTION
**Pull request by Othella**
#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.
image

**Comment by Othella** [comment]
Hey @gokaiorg . I already filled that input, and also added the CNAME record to our DNS, but https://vote.gaiadao.org/#/  displays the index Snapshot page and not the GaiaDAO space. Any clue on this? thx

**Comment by gokaiorg** [comment]
> Hey @gokaiorg. I already filled that input and the domain name one, I also added the CNAME record to our DNS, but https://vote.gaiadao.org/#/ displays the index Snapshot page and not the GaiaDAO space. Any clue on this? thx

Hey @Othella ! You need to delete images from the PR cause your images are already lives. Then I will merge your PR and your domain will be live too :) Thank you!

**Comment by Othella** [comment]
Hey @gokaiorg ! Images are now removed. Thanks!

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
