### PR TITLE
Add TreasureDAO domain and skin

### PR DESCRIPTION
**Pull request by 0xkarel**
- Add TreasureDAO skin
- Add `vote.treasure.lol` domain for `treasuredao.eth`

### CODE REVIEW

**Review by gokaiorg — CHANGES_REQUESTED** [review]
To create your skin will also need to list your skin on this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

**Comment by 0xkarel** [comment]
> To create your skin will also need to list your skin on this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

Thanks @gokaiorg, updated!

**Comment by gokaiorg** [comment]
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

**Comment by 0xkarel** [comment]
> There is a conflict in your PR since `domains.json` file has been updated, can you resolve it? To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

Updated, @gokaiorg.

**Review by gokaiorg — APPROVED** [review]

**Pull request merged**
